### ISSUE TITLE
Dev dependency issue when using wally install

### ISSUE THREAD

**Issue by Nidoxs** [ClockworkSquirrel/BasicState#10]
When using basic state with Wally (v0.3.1) and running 
> wally install

I get this error:
[https://cdn.discordapp.com/attachments/872225914149302333/921079172565172224/unknown.png](url)

I believe it's an issue with BasicState's wally.toml configuration.

Please look into fixing, much appreciated! :)

**Comment by eldonwilliams** [comment]
I created a fork that removes all dev dependencies so that way it'll work temporarily. It's not desirable, but it worked for me. Package is "eldonwilliams/basicstate" for wally. [GitHub](https://github.com/eldonwilliams/BasicState)
