### ISSUE TITLE
Support for Wally

### ISSUE THREAD

**Issue by mkargus** [ClockworkSquirrel/BasicState#9]
This provides a better alterative to manually copy and paste the script or the usage of git submodules.

**Comment by cxmeel** [comment]
Thanks for the suggestion! I had planned on adding to [wally](https://github.com/upliftgames/wally) at some point *(probably with a [Luau](https://luau-lang.org/)-focused rewrite)*. The current version (v0.2.3) is now available in the [wally registry](https://github.com/upliftgames/wally-index).
